name: Android CI


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Generate local.properties for gradle
      run: |
        cat <<EOF > local.properties
        MAPS_API_KEY="${{secrets.MAPS_API_KEY}}"
        MAPPED_IN_KEY="${{secrets.MAPPED_IN_KEY}}"
        MAPPED_IN_SECRET="${{secrets.MAPPED_IN_SECRET}}"
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run tests with Gradle
      run: ./gradlew test --stacktrace
